{% set name = "edgedb-python" %}
{% set pypi_name = "edgedb" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/edgedb-{{ version }}.tar.gz
  sha256: 93389d7adac5e03ef70c230ec3e8626a9fd697debd48b3bf3b9961efbe236865

build:
  skip: true  # [py<37]
  entry_points:
    - edgedb-py=edgedb.codegen.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - typing-extensions >=3.10.0  # [py<38]
    - certifi >=2021.5.30  # [win]

test:
  imports:
    - edgedb
  commands:
    - pip check
    - edgedb-py --help
  requires:
    - pip

about:
  home: https://github.com/edgedb/edgedb-python
  summary: EdgeDB Python driver
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neda-dtu
